export interface errors {
  err: boolean;
  status: number;
  statusText: string;
}

// Generated by https://quicktype.io

export interface FetchAllCryptos {
  id: string;
  name: string;
  symbol: string;
  rank: number;
  is_new: boolean;
  is_active: boolean;
  type: string;
}

export enum Type {
  Coin = "coin",
  Token = "token",
}
